# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

group = boatcam
version = dev

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Dependencies
fabric_version=0.160.0+26.2
modmenu_version=20.0.2
yacl_version=3.9.6+26.2-fabric
